# Generated by Django 4.1.7 on 2023-04-30 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('S_no', models.IntegerField()),
                ('Topic_Name', models.CharField(max_length=25, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(6)])),
            ],
        ),
    ]
